### ISSUE TITLE
Build FrontEnd

### ISSUE THREAD

**Issue by peppocola** [se4ai2122-cs-uniba/CT-COVID#27]
Build a simple frontend by using requests to the API.

Useful resources: [FastApi-React](https://github.com/testdrivenio/fastapi-react)

**Comment by SYED-RAFI-NAQVI** [comment]
Hello @peppocola,

I would like to work on this project. Can you please assign it to me•

**Comment by peppocola** [comment]
Hello @SYED-RAFI-NAQVI ,
this is an univeristy project, and we have already written the frontend code because it is an assignment.
If you want to make your own, feel free to fork this project and code the frontend. If it is a good frontend, we will add your code to this repository after the exam deadline.
Thanks for asking.
:D
