### ISSUE TITLE
Review Scripts

### ISSUE THREAD

**Issue by loreloc** [se4ai2122-cs-uniba/CT-COVID#48]
Review all the bash scripts in the ```scripts/``` directory.

**Comment by itsfrank98** [comment]
The scripts named `run-grafana-linux.sh`, `run-prometheus-linux.sh`, `run-prometheus.sh` can be deleted since the docker-compose runs and manages them for us

**Comment by loreloc** [comment]
I think we can merge this first into main, and then merge the ```altern_manager``` branch
